### ISSUE TITLE
Backdoor factory

### ISSUE THREAD

**Issue by shane89420** [Z4nzu/hackingtool#138]
Scenario:fatrat install

So... everything looks great til backdoor...at which point I'm stuck on stupid because it won't let me download from the Kali repository and I tried to git clone... what am I doing wrong.

**Comment by Greatest125** [comment]
I need more context. What backdoor? Why can't you git clone? Use the following template:


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
