### ISSUE TITLE
Snow10's GitHub Page is down

### ISSUE THREAD

**Issue by ibelieveinwhatileaveinthewaybehind** [Z4nzu/hackingtool#259]
**Describe the bug**
Snow10's GitHub page is down and seemingly has been for a while. Here's a mirror from the official creator: https://git.voidnet.tech/kev/snow10

**Comment by cclauss** [comment]
@ibelieveinwhatileaveinthewaybehind What is the todo for this issue?

**Comment by Baldonado901** [comment]
I'm really sorry man. I did a pull by mistake. I'm trying to study pentesting, but there is just too much. I'm taking it slow as I can. I just have a really hard time with school and I have no help. I really am confused about GitHub. I can't grasp coding. I just cant. I'm confused all the way through about coding and GitHub. Like I can just download the zip right and it goes on windows only? Or can I use your tools with Linux. I just learned Linux the best I could so I can study pentesting. Without like a mentor or someone to help it's like really frustrating because of adhd and some kind of learning disabilty. Feel super stupid that I'm just lost and overwhelm. I'm sorry for doing that pull request and wasting your time and giving you some hope. If you know any book or video that explains it in really simple terms that someone really struggling with even grasping GitHub and coding? If you do that would help me a lot. Or someone that is learning at the beginning that I could kinda study with online or where I could find someone doing that?

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 18, 2023 at 7:32 AM, Christian ***@***.***> wrote:   


@ibelieveinwhatileaveinthewaybehind What is the todo for this issue?
