### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by hmmathews** [Z4nzu/hackingtool#276]
![F7F80120-33FD-4915-98BA-3272EEA6A672](https://user-images.githubusercontent.com/95608714/182009103-7a65fedd-dbe2-4ecf-8162-5efd651d762e.png)

**Comment by veryspecialagent77** [comment]
If you're going to learn coding, you need to teach yourself to read the details because it tells you what you did wrong: You never actually installed Python or pip3.

So figure out whatever the commands are to install python 
and pip3 with iOS and do that first.

I'm going to take a shot in the dark with this one: 

If you do successfully install everything, but then can't get the tool to load up, it's because you're trying to run them from an iPhone, not realizing that those commands listed in the README are specific to the particular Linux platform the coder used to write and test the code...which, if you look at the last command you can see is Kali Linux.
