### ISSUE TITLE
Cant install hackingtool

### ISSUE THREAD

**Issue by akashrathod1998** [Z4nzu/hackingtool#7]
![Screenshot 2020-07-07 13:14:33](https://user-images.githubusercontent.com/33719389/86818056-e0873f80-c053-11ea-84d6-98904fd7e5a0.png)
Please fix problem for me..

**Comment by Z4nzu** [comment]
Please install as a root like
```
Kali@kali:~/$ sudo ./install.sh
```

**Comment by Shing-Ho** [comment]
I did using `sudo ./install.sh`
but
```
[✔] Checking directories...
[✔] Installing ...

fatal: could not create work tree dir '/usr/share/doc/hackingtool': Read-only file system
cp: /usr/bin/hackingtool: Read-only file system
[✘] Installation Failed !!! [✘]
```

**Comment by booboom** [comment]
Issues +1

**Comment by Z4nzu** [comment]
Please send me system Details with ScreenShot I'll check 👍

**Comment by Shing-Ho** [comment]
![Screen Shot 2020-07-08 at 5 48 50 AM](https://user-images.githubusercontent.com/57267692/86920489-bb8bde80-c0de-11ea-8461-0c46a394f767.png)

**Comment by akashrathod1998** [comment]
> Please send me system Details with ScreenShot I'll check

I fixed it with sudo command thnkx bro🙂😉

**Comment by Shing-Ho** [comment]
It's not working with sudo command for me.

**Comment by Z4nzu** [comment]
> ![Screen Shot 2020-07-08 at 5 48 50 AM](https://user-images.githubusercontent.com/57267692/86920489-bb8bde80-c0de-11ea-8461-0c46a394f767.png)
> 

Sorry for inconvenience.., but this tool is work on Debian Linux system because some tools in hackingtool not compatible with Mac OS I'll try to create another tool like hackingtool for Mac OS but for now you can use Virtual Box and Run it with Kali Linux 😊

**Comment by Shing-Ho** [comment]
I see, ok. :)

**Comment by Steven-dpy** [comment]
Sorry, I do not use IOS. Now, I am using win. So I do not use it.&nbsp;
Sorry, I do not have any help to you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr.Z4nzu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 晚上8:53
收件人:&nbsp;"Z4nzu/hackingtool"<hackingtool@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Z4nzu/hackingtool] Cant install hackingtool (#7)





  

  
Sorry for inconvenience.., but this tool is work on Debian Linux system because some tools in hackingtool not compatible with Mac OS I'll try to create another tool like hackingtool for Mac OS but for now you can use Virtual Box and Run it with Kali Linux
